controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

controllers_v1:
    resource:
        path: ../src/Controller/Api/V1
        namespace: App\Controller\Api\V1
    type: attribute
    prefix: /api/v1
